/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abhimanyu
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
public class management_update extends javax.swing.JFrame {
    Connection con ;
Statement stmt;
DefaultTableModel model;
int flag;

    /**
     * Creates new form management_update
     */
    public management_update() {
        initComponents();
         model=(DefaultTableModel)tblinven.getModel();
                show1();
                flag=0;
                p2.setVisible(false);
                disable1();
    }
 void OpenConnection()
{
     try{
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/grocery","root","root23");
        stmt=con.createStatement();
        }
       
       catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
           
        }
}
    public void show1()
{
        delete1();    
        model=(DefaultTableModel)tblinven.getModel();
        try{
         OpenConnection();
        
         String query="select * from project;";
         ResultSet rs=stmt.executeQuery(query);
         while(rs.next())
         {
             
             String productID=rs.getString("product_id");
             String productname=rs.getString("product_name");
             String vendorname=rs.getString("vendor_name");
             String expirationdate=rs.getString("expiration_date");
             String quantity=rs.getString("quantity");
             
             
             
             
             model.addRow(new Object[] {productID,productname,vendorname,expirationdate,quantity});
         }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e){
                 JOptionPane.showMessageDialog(null, e.getMessage());
                
             }
}
    void delete1()
{
    int rows=model.getRowCount();
    if (rows>0){
        for (int i=0;i<rows;i++){
            model.removeRow(0);
        }
    }
}
    void clear()
  {
    txtpname.setText("") ;
    txtpid.setText(""); 
    txtvname.setText("") ;
    txtquantity.setText("") ;
    txtexpire.setText("") ;
   
  }
  void disable1()
  {
   txtpname.setEnabled(false) ;
    txtpid.setEnabled(false); 
    txtvname.setEnabled(false) ;
    txtquantity.setEnabled(false) ;
    txtexpire.setEnabled(false);
   
  }
  void enabled1()
  {
      txtpname.setEnabled(true) ;
    txtpid.setEnabled(true); 
    txtvname.setEnabled(true) ;
    txtquantity.setEnabled(true) ;
    txtexpire.setEnabled(true);
   
    
  }
   void setdata(String h)
   {
        try
        {
             OpenConnection();
             String query="Select * from project where product_id='" + h.toUpperCase()+ "';";
             ResultSet rs=stmt.executeQuery(query);
             if(rs.next())
             { 
                 txtpid.setText(rs.getString("product_id")) ;
                 txtpname.setText(rs.getString("product_name"));
                 txtvname.setText(rs.getString("vendor_name")) ;
                 txtexpire.setText(rs.getString("expiration_date"));
                 txtquantity.setText(rs.getString("quantity")) ;
                 
                
             }
        }

catch(Exception e)
       {
         JOptionPane.showMessageDialog(null, e.getMessage());
   }
    
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpid = new javax.swing.JTextField();
        txtpname = new javax.swing.JTextField();
        txtvname = new javax.swing.JTextField();
        txtexpire = new javax.swing.JTextField();
        txtquantity = new javax.swing.JTextField();
        p2 = new javax.swing.JPanel();
        BTNUPDATE = new javax.swing.JButton();
        BTNCANCLE = new javax.swing.JButton();
        p1 = new javax.swing.JPanel();
        BTNEDIT = new javax.swing.JButton();
        BTNDELETE = new javax.swing.JButton();
        BTNEXIT = new javax.swing.JButton();
        BTNBACK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinven = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("ENTRY UPDATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 13, 191, 34));

        jLabel2.setText("PRODUCT ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 116, 108, 29));

        jLabel3.setText("PRODUCT NAME:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 198, 108, 36));

        jLabel4.setText("VENDOR NAME:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 275, 108, 38));

        jLabel5.setText("EXPIRATION DATE:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 359, 108, 39));

        jLabel6.setText("QUANTITY:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 429, 108, 33));
        getContentPane().add(txtpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 110, 137, 40));

        txtpname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 196, 137, 41));
        getContentPane().add(txtvname, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 269, 137, 50));
        getContentPane().add(txtexpire, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 354, 137, 49));

        txtquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantityActionPerformed(evt);
            }
        });
        getContentPane().add(txtquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 137, 46));

        p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BTNUPDATE.setText("UPDATE");
        BTNUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUPDATEActionPerformed(evt);
            }
        });

        BTNCANCLE.setText("CANCLE");
        BTNCANCLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCANCLEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNUPDATE)
                    .addComponent(BTNCANCLE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNUPDATE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(BTNCANCLE)
                .addContainerGap())
        );

        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 312, -1, -1));

        p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BTNEDIT.setText("EDIT");
        BTNEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITActionPerformed(evt);
            }
        });

        BTNDELETE.setText("DELETE");
        BTNDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDELETEActionPerformed(evt);
            }
        });

        BTNEXIT.setText("EXIT");
        BTNEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNEDIT)
                    .addComponent(BTNEXIT))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(p1Layout.createSequentialGroup()
                .addComponent(BTNDELETE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNEDIT)
                .addGap(35, 35, 35)
                .addComponent(BTNDELETE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(BTNEXIT))
        );

        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 90, 160));

        BTNBACK.setText("BACK");
        BTNBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBACKActionPerformed(evt);
            }
        });
        getContentPane().add(BTNBACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, -1, -1));

        tblinven.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "productid", "productname", "vendorname", "expirationdate", "quantity"
            }
        ));
        jScrollPane1.setViewportView(tblinven);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 620, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpnameActionPerformed

    private void txtquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantityActionPerformed

    private void BTNBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBACKActionPerformed
       managementframe_main c1=new managementframe_main();
c1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTNBACKActionPerformed

    private void BTNEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEXITActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_BTNEXITActionPerformed

    private void BTNDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDELETEActionPerformed
      
        String x=JOptionPane.showInputDialog("Enter the product id to Delete");
        setdata(x);
        if (x.compareTo("")!=0) {
            int ans=JOptionPane.showConfirmDialog(null,"ARE YOU  Sure YOU WANT TO Delete!!!");
            if (ans==JOptionPane.YES_OPTION) {
                try {
                    OpenConnection();

                    String query="Delete from project where product_id='" + txtpid.getText() + "';";
                    stmt.executeUpdate(query);

                    stmt.close();
                    con.close();

                    JOptionPane.showMessageDialog(null, "Record Deleted !!!");
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null,e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Record Not Deleted !!!");
            }
            show1();
            clear();
        } else {
            JOptionPane.showMessageDialog(null, "Record Not Found !!!");
        }
    }//GEN-LAST:event_BTNDELETEActionPerformed

    private void BTNEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITActionPerformed
        try{
            String x=JOptionPane.showInputDialog("Enter the product id to modify");
            if ( x.compareTo("")!=0)
            {
                setdata(x);

                p1.setVisible(false);
                p2.setVisible(true);
            }
            flag=1;
            enabled1();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Record Not Found !!!");
        }
        
    }//GEN-LAST:event_BTNEDITActionPerformed

    private void BTNUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUPDATEActionPerformed
        enabled1();
        try { String query=null;
            if ((txtpid.getText()).compareTo("")!=0 && (txtpname.getText()).compareTo("")!=0 && (txtvname.getText())!="" && (txtexpire.getText())!="" && (txtquantity.getText()).compareTo("")!=0)
            {
                
                OpenConnection();
               if(flag==1)
               {
                    query="update project set product_id='" + txtpid.getText() + "',product_name='" + txtpname.getText() + "',vendor_name='" + txtvname.getText() + "',expiration_date='" + txtexpire.getText() + "',quantity='" + txtquantity.getText() +"'where  product_id='" + txtpid.getText() +  "';";

                    JOptionPane.showMessageDialog(null, "Record modified !!!");
               }
                
                stmt.executeUpdate(query);
                stmt.close();
                con.close();
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Fields Empty");
                p2.setVisible(false);
                p1.setVisible(true);
            }
             p2.setVisible(false);
                p1.setVisible(true);
            show1();
            
            clear();
            disable1();
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } 
    }//GEN-LAST:event_BTNUPDATEActionPerformed

    private void BTNCANCLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCANCLEActionPerformed
      clear();
        disable1();
        p2.setVisible(false);
        p1.setVisible(true);
    }//GEN-LAST:event_BTNCANCLEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(management_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(management_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(management_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(management_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new management_update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBACK;
    private javax.swing.JButton BTNCANCLE;
    private javax.swing.JButton BTNDELETE;
    private javax.swing.JButton BTNEDIT;
    private javax.swing.JButton BTNEXIT;
    private javax.swing.JButton BTNUPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JTable tblinven;
    private javax.swing.JTextField txtexpire;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtpname;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txtvname;
    // End of variables declaration//GEN-END:variables
}
