/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abhimanyu
 */
public class managementframe_main extends javax.swing.JFrame {

    /**
     * Creates new form managementframe_main
     */
    public managementframe_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        menubar1 = new javax.swing.JMenuBar();
        menuexit = new javax.swing.JMenu();
        menunew = new javax.swing.JCheckBoxMenuItem();
        menuview = new javax.swing.JCheckBoxMenuItem();
        menuupdate = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menubar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuexit.setText("INVENTORY MANAGEMENT SYSTEM");
        menuexit.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        menuexit.setOpaque(true);

        menunew.setSelected(true);
        menunew.setText("NEW ENTRY");
        menunew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunewActionPerformed(evt);
            }
        });
        menuexit.add(menunew);

        menuview.setSelected(true);
        menuview.setText("VIEW STATUS");
        menuview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuviewActionPerformed(evt);
            }
        });
        menuexit.add(menuview);

        menuupdate.setSelected(true);
        menuupdate.setText("UPDATE");
        menuupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuupdateActionPerformed(evt);
            }
        });
        menuexit.add(menuupdate);

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("EXIT");
        jCheckBoxMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem4ActionPerformed(evt);
            }
        });
        menuexit.add(jCheckBoxMenuItem4);

        menubar1.add(menuexit);

        setJMenuBar(menubar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuupdateActionPerformed
        management_update e1=new management_update();
        e1.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_menuupdateActionPerformed

    private void menunewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menunewActionPerformed
       mangement_new z1= new mangement_new();
       z1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menunewActionPerformed

    private void jCheckBoxMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem4ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jCheckBoxMenuItem4ActionPerformed

    private void menuviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuviewActionPerformed
        management_view d1=new management_view();
        d1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managementframe_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managementframe_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managementframe_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managementframe_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managementframe_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JMenuBar menubar1;
    private javax.swing.JMenu menuexit;
    private javax.swing.JCheckBoxMenuItem menunew;
    private javax.swing.JCheckBoxMenuItem menuupdate;
    private javax.swing.JCheckBoxMenuItem menuview;
    // End of variables declaration//GEN-END:variables
}
